### ISSUE TITLE
JS Error "SyntaxError: expected expression, got '&'"

### ISSUE THREAD

**Issue by hidnasio** [cherta/js.uy#11]
I get this error in the console when I open the site in Firefox and Chrome on Mac.

<img width="1280" alt="screen shot 2017-04-13 at 6 50 19 pm" src="https://cloud.githubusercontent.com/assets/2262669/25025986/e17f5d90-207a-11e7-927c-86f82e747dfb.png">

**Comment by cherta** [comment]
🤔 I wonder what's causing it, will investigate

**Comment by ercpereda** [comment]
Markdown escape the quotes inside a `script` tag. I created a shortcode and move the mailchimp form inside it.
