### ISSUE TITLE
[Proposal] Add 'The Montevideo Javascript Meetup Group' to the list

### ISSUE THREAD

**Issue by francocorreasosa** [cherta/js.uy#7]
I propose deploying [this site](http://mvd-js-dev.vaus1.francocorrea.com.uy) (still in dev) to now.sh and link it to `mvd.js.uy`.

It is connected to Meetup.com and will update automatically 😄

**Comment by cherta** [comment]
@francocorreasosa if you host it on `now.sh` the only way you can get a custom domain is by paying a monthly fee to `now`. We have the same issue with `reactjsuy.now.sh`.

If you PR the meetup logo after I merge #6 I'll be happy to add it to the community list.

**Comment by cherta** [comment]
I can still point `mvd.js.uy` to any IP you want anyway

**Comment by francocorreasosa** [comment]
Can you add a `CNAME` record pointing to `https://francocorreasosa.github.io/mvd-dot-js/`?. I'll deploy a ⚛️ app that hits the meetup.com API there.

**Comment by cherta** [comment]
I need the IP @francocorreasosa, Antel DNS does not support servers but IPs only. I can point the CNAME to github pages IP which is `192.30.252.153`.

**Comment by francocorreasosa** [comment]
Let's try 👍

**Comment by cherta** [comment]
Done, now we need to wait for the DNS propagation, usually 24hs or less in my experience

**Comment by francocorreasosa** [comment]
No problem, thanks! 👏

**Comment by francocorreasosa** [comment]
The site is ready! 🙌 http://mvd.js.uy/
